### ISSUE TITLE
Mangle 3.0 Stability - Cassandra DB goes down suddenly

### ISSUE THREAD

**Issue by Anvesh42** [vmware/mangle#105]
**Environment:** OpenShift v4.6.36
**Kubernetes Version:** v1.19.0
**Mangle Version:** 3.0
**Issue:**

1. Cassandra DB goes down with failed connections causing mangle POD to do multiple retries on the cassandra DB
2. Mangle product UI is not available for this entire duration

**Interim Solution Being Followed:**

1. Restart Cassandra POD
2. Restart mangle POD
3. Increase the resource limits on cassandra statefulset template as recommended by the mangle team during working session.

**Previous:**
```
 - resources:
       limits:
           cpu: '1'
           memory: 8Gi
        requests:
           cpu: '500m'
           memory: 2Gi
```

**Current:**
```
 - resources:
       limits:
           cpu: '2'
           memory: 8Gi
        requests:
           cpu: '1'
           memory: 4Gi
```

**Frequency Of This Issue:** Once every few weeks. Typically 7-8 weeks but it may be random too.

**Logs:**

1. Please find the attached logs from mangle & cassandra POD's when this issue downtime happened recently in the last week of February, 2022

[cassandra_pod_failure_0227.txt](https://github.com/vmware/mangle/files/8254981/cassandra_pod_failure_0227.txt)
[mangle_pod_failure_0227.txt](https://github.com/vmware/mangle/files/8254982/mangle_pod_failure_0227.txt)

**Deployment Templates:**

1. Please find the attached cassandra statefulset & mangle deployment template resource
[cassandra_statefulset_template.txt](https://github.com/vmware/mangle/files/8255000/cassandra_statefulset_template.txt)
[mangle_deployment_template.txt](https://github.com/vmware/mangle/files/8255001/mangle_deployment_template.txt)
